-- Create Database
CREATE DATABASE IF NOT EXISTS cdac_db;
USE cdac_db;

-- 1. Roles Table
CREATE TABLE IF NOT EXISTS roles (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE -- 'ROLE_STUDENT', 'ROLE_FACULTY', 'ROLE_ADMIN'
);

-- 2. Users Table (Base for all actors)
CREATE TABLE IF NOT EXISTS users (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    phone VARCHAR(15),
    role_id INT NOT NULL,
    active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (role_id) REFERENCES roles(id)
);

-- 3. Student Details (Extension of Users)
CREATE TABLE IF NOT EXISTS student_details (
    user_id BIGINT PRIMARY KEY,
    enrollment_no VARCHAR(50) UNIQUE NOT NULL,
    course_name VARCHAR(100), -- Example: 'PG-DAC'
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 4. Faculty Details (Extension of Users)
CREATE TABLE IF NOT EXISTS faculty_details (
    user_id BIGINT PRIMARY KEY,
    department VARCHAR(100),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 5. Subjects/Courses
CREATE TABLE IF NOT EXISTS subjects (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(20) NOT NULL UNIQUE
);

-- 6. Timetable
CREATE TABLE IF NOT EXISTS timetable (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    subject_id BIGINT NOT NULL,
    faculty_id BIGINT NOT NULL, -- references users(id) because faculty is a user
    day_of_week VARCHAR(10) NOT NULL, -- 'MONDAY', etc.
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    room_number VARCHAR(20),
    FOREIGN KEY (subject_id) REFERENCES subjects(id),
    FOREIGN KEY (faculty_id) REFERENCES users(id)
);

-- 7. QR Sessions (Generated by Faculty for Attendance)
CREATE TABLE IF NOT EXISTS qr_sessions (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    faculty_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    token VARCHAR(255) NOT NULL UNIQUE, -- The content of the QR code
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    FOREIGN KEY (faculty_id) REFERENCES users(id),
    FOREIGN KEY (subject_id) REFERENCES subjects(id)
);

-- 8. Attendance Records
CREATE TABLE IF NOT EXISTS attendance (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    student_id BIGINT NOT NULL, -- references users(id)
    qr_session_id BIGINT NOT NULL,
    status VARCHAR(20) DEFAULT 'PRESENT',
    marked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES users(id),
    FOREIGN KEY (qr_session_id) REFERENCES qr_sessions(id)
);

-- 9. Leave Requests
CREATE TABLE IF NOT EXISTS leave_requests (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    student_id BIGINT NOT NULL,
    reason TEXT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(20) DEFAULT 'PENDING', -- PENDING, APPROVED, REJECTED
    applied_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (student_id) REFERENCES users(id)
);

-- Insert Default Roles
INSERT INTO roles (name) VALUES ('ROLE_STUDENT'), ('ROLE_FACULTY'), ('ROLE_ADMIN') ON DUPLICATE KEY UPDATE name=name;

-- Insert Default Admin (Password: admin123) - Encoded BCrypt needed, but for SQL script just placeholder or known hash.
-- $2a$10$D7.v61wW1/y.i/.. (example hash for 'password')
-- I will leave user insertion for the Application Initializer or Manual.
